// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCt5NvtTb4l2d-qZhNLcPK4liv1ru3VSYQ',
    appId: '1:661362131585:android:4444891b00382b6d438380',
    messagingSenderId: '661362131585',
    projectId: 'techford-chat1',
    storageBucket: 'techford-chat1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ4n476REfSepnffti3bG5DTeDLWIVXEI',
    appId: '1:661362131585:ios:c272176bb795bc35438380',
    messagingSenderId: '661362131585',
    projectId: 'techford-chat1',
    storageBucket: 'techford-chat1.appspot.com',
    androidClientId: '661362131585-vuki3soihh6m9shktuh7omc35rpb0air.apps.googleusercontent.com',
    iosClientId: '661362131585-imdoj9mdstjj891o1h6p5oaci6rfvbm6.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );
}
